"""
Django settings for AgroControl project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!ycll)+ggco424vwsyhs#!v#q=lgc7k@#2acn30#vi6c=z6&mw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'autenticacion',
    'cuarteles', 
    'riego',
    'aplicaciones',
    'mantenimiento',
    'inventario',
    'reportes',
    'ordenes_trabajo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgroControl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgroControl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'agrocontrol',
        'USER': 'postgres',
        'PASSWORD': 'agrocontrol',
        'HOST': 'agrocontrol-db.c12msmcq8dsc.us-east-2.rds.amazonaws.com',
        'PORT': '5432',
    }
}

# Configuración para login/logout
LOGIN_URL = '/login/'  # ⬅️ Tu URL de login
LOGOUT_REDIRECT_URL = '/login/'  # ⬅️ Donde redirigir después del logout

# ==============================================
#  CONFIGURACIÓN DE SESIONES (AgroControl)
# ==============================================

# 1. Duración de la sesión (en segundos)
# 3600 = 1 hora. 
# Si el usuario no hace nada en 1 hora, se le cerrará la sesión.
SESSION_COOKIE_AGE = 3600 

# 2. ¿Cerrar sesión al cerrar el navegador?
# True = Si cierra Chrome/Edge, tiene que loguearse de nuevo (Más seguro).
# False = Puede cerrar y abrir el navegador y seguir logueado (Más cómodo).
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 3. Renovar la sesión con actividad
# True = Si el usuario hace click, el contador de 1 hora se reinicia.
# (Es lo ideal para que no se le cierre mientras trabaja).
SESSION_SAVE_EVERY_REQUEST = True

# 4. Seguridad (Para producción/HTTPS)
# Ponlos en True cuando subas a Render y tengas HTTPS activado.
# SESSION_COOKIE_SECURE = True 
# CSRF_COOKIE_SECURE = True
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuración de archivos media (para certificaciones)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# settings.py
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_DOMAIN = None  # Para desarrollo local
SESSION_COOKIE_PATH = '/'
SESSION_SAVE_EVERY_REQUEST = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]