"""
Django settings for AgroControl project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url  # <--- NUEVO: Para conectar la BD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# SEGURIDAD Y ENTORNO (MODIFICADO PARA RENDER)
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# Intenta leer de Render, si no, usa la tuya por defecto
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!ycll)+ggco424vwsyhs#!v#q=lgc7k@#2acn30#vi6c=z6&mw')

# SECURITY WARNING: don't run with debug turned on in production!
# Si estamos en Render, DEBUG será False. En tu PC será True.
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# === AGREGA ESTO JUSTO DEBAJO ===
# Esto es OBLIGATORIO para que funcione el login en Render
CSRF_TRUSTED_ORIGINS = []
if RENDER_EXTERNAL_HOSTNAME:
    # Django necesita que le especifiques 'https://'
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'storages',
    'autenticacion',
    'cuarteles', 
    'riego',
    'aplicaciones',
    'mantenimiento',
    'inventario',
    'reportes',
    'ordenes_trabajo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- NUEVO: Para los estilos CSS en Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgroControl.urls'

# NOTA: Tenías TEMPLATES duplicado en tu código original. 
# He dejado solo este bloque, que es el que tiene la configuración correcta de 'DIRS'.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgroControl.wsgi.application'


# ==============================================================================
# BASE DE DATOS (MODIFICADO PARA RENDER)
# ==============================================================================
# Aquí configuramos para que use tu BD de AWS por defecto.
# Render buscará la variable DATABASE_URL, si no la halla, usa tu string de conexión explícito.

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:agrocontrol@agrocontrol-db.c12msmcq8dsc.us-east-2.rds.amazonaws.com:5432/agrocontrol',
        conn_max_age=600
    )
}


# Configuración para login/logout
LOGIN_URL = '/login/'  
LOGOUT_REDIRECT_URL = '/login/' 

# ==============================================
#  CONFIGURACIÓN DE SESIONES (AgroControl)
# ==============================================

# 1. Duración de la sesión (en segundos)
SESSION_COOKIE_AGE = 3600 

# 2. ¿Cerrar sesión al cerrar el navegador?
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 3. Renovar la sesión con actividad
SESSION_SAVE_EVERY_REQUEST = True

# 4. Seguridad (Para producción/HTTPS)
# Esto se activa solo si DEBUG es False (es decir, en Render)
if not DEBUG:
    SESSION_COOKIE_SECURE = True 
    CSRF_COOKIE_SECURE = True

# Nombre de cookie
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_DOMAIN = None  
SESSION_COOKIE_PATH = '/'


# ==========================================
# CONFIGURACIÓN DE CORREO (Gmail)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreplyagrocontrol@gmail.com' 
EMAIL_HOST_PASSWORD = 'uzmm flrg qoii hznl' 
DEFAULT_FROM_EMAIL = 'AgroControl <noreplyagrocontrol@gmail.com>'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================================================================
# STATIC & MEDIA FILES (CONFIGURACIÓN HÍBRIDA AWS S3 + WHITENOISE)
# ==============================================================================

# 1. Archivos Estáticos (CSS, JS, Imágenes del sistema) - Se quedan en Render
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 2. Configuración de Almacenamiento (Django 4.2+)
STORAGES = {
    # Estáticos: Usan WhiteNoise (Rápido y eficiente en Render)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    # Media (Uploads de usuarios): Se van a AWS S3
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
}

# 3. Configuración AWS S3 (Solo se activa si están las variables de entorno)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = 'us-east-2' # Tu región (Ohio)

if AWS_ACCESS_KEY_ID:
    # Configuraciones extra para S3
    AWS_S3_FILE_OVERWRITE = False # No sobrescribir archivos con el mismo nombre
    AWS_DEFAULT_ACL = None # Usar políticas del bucket (Privado por defecto)
    AWS_S3_VERIFY = True
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # Esto genera URLs temporales firmadas (seguridad para los certificados)
    # El enlace caducará después de un tiempo (por defecto 1 hora)
    AWS_QUERYSTRING_AUTH = True 
    AWS_S3_ADDRESSING_STYLE = "virtual"
    
    # Opcional: Límite de tamaño (5MB = 5242880 bytes)
    AWS_S3_MAX_MEMORY_SIZE = 5242880 
    
else:
    # Fallback para desarrollo local si no has puesto las claves todavía
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'